### ISSUE TITLE
Getting ssl handshake error

### ISSUE THREAD

**Issue by shubhamitc** [liangrog/admission-webhook-server#9]
Hi , i am getting the below ssl handshake error. Pleaes suggest how to solve this. 

**installation step**

```
helm upgrade --install admission-webhook-server  .  --recreate-pods
```

**values.yaml**
```
---
# Override resource name
#nameOverride

# Override url base path. Default to mutate
#basePathOverride:

# PodNodesSelector
# Override podnodeselector handler path. Default to pod-nodes-selector
#podNodesSelectorPathOverride:
# Confiruation for podnodesselector. The namespace and labels are set here following the format:
#   namespace: key=label,key=label; namespace2: key=label
#podNodesSelectorPathOverride:
# Confiruation for podnodesselector. The namespace and labels are set here following the format:
#  echoserver: deploymenttype=blue
# Note: Multiple namespaces seperate by ;
#
# Examples:
#   devel: node-role.kubernetes.io/development=true, beta.kubernetes.io/instance-type=t3.large
podNodesSelectorConfig:
  echoserver: deploymentType=blue

service:
  # the service is important. It forms part of the CN for SSL certificate.
  name: admission-webhook
  #type:
  annotations: {}

replicas: 1

strategy:
  type: RollingUpdate

image: liangrog/admission-webhook-server
imageTag: latest
imagePullPolicy: Always
```
http: TLS handshake error from 172.29.120.183:46270: remote error: tls: bad certificate
```

**Comment by liangrog** [comment]
User client issue, not related to admission controller.

**Comment by Xachman** [comment]
I know this old but trying this out I get this error as well. I updated the MutatingWebhookConfiguration to work on more recent versions of kubernetes. I have also updated the service hostname to match the namespace and all. But I still get this error. Is there any insight I can get on this error or troubleshooting tips?

**Comment by Xachman** [comment]
So the main tip I found is that you need to look at the Kubernetes api server logs. There you will find relevant errors to your admission controller as far as tls connection errors like this. The issue I had was that the api server was saying there were no names supplied in the cert. As it turns out it seems to only care about the Subject Alternative Names and not the Common Name. I was able to fix this by adding one to the bash script and running with bash rather than sh.

https://github.com/Xachman/admission-webhook-server/blob/master/ssl.sh#L24
